version: '3.9'  

networks:
  app-tier:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/24
          gateway: 172.20.0.1

services:

  db:
    image: mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password  
    ports:
      - 3306:3306
    volumes:
      - ./php-mysql-crud/database/script.sh:/docker-entrypoint-initdb.d/dump.sh
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_PW}"
      DB_NAME: "${DB_NAME}"
      DB_USER: "${DB_USER}"
      DB_PW: "${DB_PW}"
    networks:
      app-tier:
        ipv4_address: 172.20.0.2

  web:
    build:
      context: ./
      dockerfile: Dockerfile  
    restart: always
    ports:
      - 8100:8888
    volumes:
      - ./php-mysql-crud:/var/www/html/
    env_file: .env
    networks:
      app-tier:
        ipv4_address: 172.20.0.3
    depends_on:
      - "db"