mysql --user=root --password=$MYSQL_ROOT_PASSWORD --execute "
CREATE DATABASE $DB_NAME;use $DB_NAME;
CREATE TABLE task(id INT(11) PRIMARY KEY AUTO_INCREMENT,title VARCHAR(255) NOT NULL,description TEXT,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
DESCRIBE task;
CREATE USER '$DB_USER'@'%' IDENTIFIED BY '$DB_PW';
GRANT ALL PRIVILEGES ON $DB_NAME.* TO '$DB_USER'@'%';"