# -*- mode: ruby -*-
# vi: set ft=ruby :

PROJECT_NAME = "ROUTE"
PREFIX = "T30"
Vagrant.configure("2") do |config|

  # NAT
  
    config.vm.define "#{PROJECT_NAME}_NAT" do |conf| 
    conf.vm.box = "ubuntu/focal64"
    conf.vm.hostname = "EPAMKHAW-NAT-#{PROJECT_NAME}.local"
    conf.vm.network "private_network", ip: "172.16.14.3", netmask: "255.255.255.0", virtualbox__intnet: "net-2"
    conf.vm.network "public_network"

    conf.vm.provider "virtualbox" do |vb|
      vb.name = "NAT"
      vb.gui = true
      vb.memory = 1024
      vb.cpus = 2
      # vb.customize ["modifyvm", :id, "--groups", "/#{PROJECT_NAME}"]
    end
    
    conf.vm.provision "shell", path: "./NAT/nat_disable.sh"
    conf.vm.provision "shell", path: "./NAT/NAT.sh"
    conf.vm.provision "Iptables-persistent", type: "shell", inline: <<-SHELL
      sudo su
      apt update
      DEBIAN_FRONTEND=noninteractive apt install iptables-persistent -y
    SHELL
  end

  # DNS Server

    config.vm.define "#{PROJECT_NAME}_DNS" do |conf| 
    conf.vm.box = "ubuntu/focal64"
    conf.vm.hostname = "EPAMKHAW-DNS-#{PROJECT_NAME}.local"
    conf.vm.network "private_network", ip: "172.16.14.4", netmask: "255.255.255.0", virtualbox__intnet: "net-2"

    conf.vm.provider "virtualbox" do |vb|
      vb.name = "DNS"
      vb.gui = true
      vb.memory = 1024
      vb.cpus = 2
      # vb.customize ["modifyvm", :id, "--groups", "/#{PROJECT_NAME}"]
    end
    
    conf.vm.provision "shell", path: "./NAT/nat_disable.sh"
    conf.vm.provision "shell", path: "./DNS/dns.sh"
  end

  # DHCP Server

    config.vm.define "#{PROJECT_NAME}_DHCP" do |conf|
    conf.vm.box = "ubuntu/focal64"
    conf.vm.hostname = "EPAMKHAW-DHCP-#{PROJECT_NAME}.local"
    conf.vm.network "private_network", ip: "172.16.14.2", netmask: "255.255.255.0", virtualbox__intnet: "net-2"

    conf.vm.provider "virtualbox" do |vb|
      vb.name = "DHCP Server"
      vb.gui = true
      vb.memory = 1024
      vb.cpus = 2
      # vb.customize ["modifyvm", :id, "--groups", "/#{PROJECT_NAME}"]
    end

    conf.vm.provision "shell", path: "./NAT/nat_disable.sh"
    conf.vm.provision "routing", type: "shell", path: "DHCP/DHCP.sh"
  end

  # R12

  config.vm.define "#{PROJECT_NAME}_R12" do |conf|
  conf.vm.box = "ubuntu/focal64"
  config.vm.box_version = "20210210.0"
  conf.vm.hostname = "EPUAKHAW1543#{PREFIX}-R12-#{PROJECT_NAME}.local"
  conf.vm.network "private_network", ip: "172.16.13.254", netmask: "255.255.255.0", virtualbox__intnet: "net-1" #, auto_config: false
  conf.vm.network "private_network", ip: "172.16.14.254", netmask: "255.255.255.0", virtualbox__intnet: "net-2" #, auto_config: false

    conf.vm.provider "virtualbox" do |vb|
      vb.name = "R12"
      vb.gui = true
      vb.memory = (512 * 2) * 1 # 4096
      vb.cpus = 2

      # vb.customize ["modifyvm", :id, "--groups", "/#{PROJECT_NAME}"]
      vb.customize ["modifyvm", :id, "--graphicscontroller", "vboxsvga"]
    end

    conf.vm.provision "shell", path: "./NAT/nat_disable.sh"
    conf.vm.provision "routing", type: "shell", inline: <<-SHELL
      sudo su
      echo "net.ipv4.ip_forward = 1" > /etc/sysctl.d/60-routing.conf

      sysctl --system
      sudo ip route add default via 172.16.14.3

      ip addres
      ip route
    SHELL

    conf.vm.provision "DHCP_relay", type: "shell", inline: <<-SHELL
      sudo su
      apt update
      DEBIAN_FRONTEND=noninteractive apt install isc-dhcp-relay -y
      echo SERVERS=\\"172.16.14.2\\" > /etc/default/isc-dhcp-relay 
      echo INTERFACES=\\"enp0s8 enp0s9\\" >> /etc/default/isc-dhcp-relay
      systemctl enable isc-dhcp-relay
      systemctl start isc-dhcp-relay

      sudo ip route add 172.16.15.0/24 via 172.16.14.253
      sudo ip route add 172.16.16.0/24 via 172.16.14.252
    SHELL
  end

  # R23

  config.vm.define "#{PROJECT_NAME}_R23" do |conf|
  # conf.vbguest.auto_update = false
  config.vm.box = "ubuntu/focal64"
  conf.vm.hostname = "EPUAKHAW1543#{PREFIX}--R23-#{PROJECT_NAME}.local"
  conf.vm.network "private_network", ip: "172.16.15.254", netmask: "255.255.255.0", virtualbox__intnet: "net-3"
  conf.vm.network "private_network", ip: "172.16.14.253", netmask: "255.255.255.0", virtualbox__intnet: "net-2"

    conf.vm.provider "virtualbox" do |vb|
      vb.name = "R23"
      vb.gui = true
      vb.memory = (512 * 2) * 1 # 4096
      vb.cpus = 2

      # vb.customize ["modifyvm", :id, "--groups", "/#{PROJECT_NAME}"]
      vb.customize ["modifyvm", :id, "--graphicscontroller", "vboxsvga"]
    end

    conf.vm.provision "shell", path: "./NAT/nat_disable.sh"
    conf.vm.provision "routing", type: "shell", inline: <<-SHELL
      sudo su
      echo "net.ipv4.ip_forward = 1" > /etc/sysctl.d/60-routing.conf
      sysctl --system
      ip route add default via 172.16.14.3

      ip addres
      ip route
    SHELL

    conf.vm.provision "DHCP_relay", type: "shell", inline: <<-SHELL
      sudo su
      apt update
      DEBIAN_FRONTEND=noninteractive apt install isc-dhcp-relay -y
      echo SERVERS=\\"172.16.14.2\\" > /etc/default/isc-dhcp-relay 
      echo INTERFACES=\\"enp0s8 enp0s9\\" >> /etc/default/isc-dhcp-relay
      systemctl enable isc-dhcp-relay
      systemctl start isc-dhcp-relay

      sudo ip route add 172.16.13.0/24 via 172.16.14.254
    SHELL
  end

  # R_DMZ

  config.vm.define "#{PROJECT_NAME}_R.DMZ" do |conf|
  conf.vm.box = "ubuntu/focal64"
  config.vm.box_version = "20210210.0"
  conf.vm.hostname = "EPUAKHAW1543#{PREFIX}-R.DMZ-#{PROJECT_NAME}.local"
  conf.vm.network "private_network", ip: "172.16.14.252", netmask: "255.255.255.0", virtualbox__intnet: "net-2" #, auto_config: false
  conf.vm.network "private_network", ip: "172.16.16.254", netmask: "255.255.255.0", virtualbox__intnet: "DMZ-Zone" #, auto_config: false
  
    # conf.vm.synced_folder "../data", "/vagrant_data"

    conf.vm.provider "virtualbox" do |vb|
      vb.name = "R.DMZ"
      vb.gui = true
      vb.memory = (512 * 2) * 1 # 4096
      vb.cpus = 2

      # vb.customize ["modifyvm", :id, "--groups", "/#{PROJECT_NAME}"]
      vb.customize ["modifyvm", :id, "--graphicscontroller", "vboxsvga"]
    end

    conf.vm.provision "shell", path: "./NAT/nat_disable.sh"
    conf.vm.provision "routing", type: "shell", inline: <<-SHELL
      sudo su
      echo "net.ipv4.ip_forward = 1" > /etc/sysctl.d/60-routing.conf

      sysctl --system
      sudo ip route add default via 172.16.14.3

      ip addres
      ip route
    SHELL

    conf.vm.provision "DHCP_relay", type: "shell", inline: <<-SHELL
      sudo su
      apt update
      DEBIAN_FRONTEND=noninteractive apt install isc-dhcp-relay -y
      echo SERVERS=\\"172.16.14.2\\" > /etc/default/isc-dhcp-relay 
      echo INTERFACES=\\"enp0s8 enp0s9\\" >> /etc/default/isc-dhcp-relay
      systemctl enable isc-dhcp-relay
      systemctl start isc-dhcp-relay

      sudo ip route add 172.16.15.0/24 via 172.16.14.253
      sudo ip route add 172.16.13.0/24 via 172.16.14.254
    SHELL
    conf.vm.provision "shell", path: "./R_DMZ/iptables.sh"
    conf.vm.provision "Iptables-persistent", type: "shell", inline: <<-SHELL
    sudo su
    apt update
    DEBIAN_FRONTEND=noninteractive apt install iptables-persistent -y
  SHELL
  end

  # N1H1

  config.vm.define "#{PROJECT_NAME}_N1H1" do |conf|
  # conf.vm.vbguest.auto_update = false
  config.vm.box = "ubuntu/focal64"
  conf.vm.hostname = "EPUAKHAW1543#{PREFIX}--N1H1-#{PROJECT_NAME}.local"
  conf.vm.network "private_network", type: "dhcp", netmask: "255.255.255.0", virtualbox__intnet: "net-1"
    
    conf.vm.provider "virtualbox" do |vb|
      vb.name = "N1H1"
      vb.gui = true
      vb.memory = (512 * 2) * 1 # 4096
      vb.cpus = 2
    
      # vb.customize ["modifyvm", :id, "--groups", "/#{PROJECT_NAME}"]
      vb.customize ["modifyvm", :id, "--graphicscontroller", "vboxsvga"]
    end
    # DHCP Config
    conf.vm.provision "shell", path: "./NAT/nat_disable.sh"
    conf.vm.provision "DHCP_netplan", type: "file", source: "DHCP/netplan_DHCP.yaml", destination: "/tmp/vagrant_task5/etc/netplan/60-task5.yaml"
    conf.vm.provision "DHCP_cloud_init", type: "file", source: "DHCP/50-cloud-init.yaml", destination: "/tmp/vagrant_task5/etc/netplan/50-cloud-init.yaml"
    conf.vm.provision "DHCP_ubuntu", type: "shell", inline: <<-SHELL
      cp -r /tmp/vagrant_task5/* /
      netplan apply
      sleep 3
    SHELL

    conf.vm.provision "routing", type: "shell", inline: <<-SHELL
      ip route add 172.16.15.0/24 via 172.16.13.254
      ip route add 172.16.14.0/24 via 172.16.13.254

      ip addres
      ip route
    SHELL
  end

  # N1H2

  config.vm.define "#{PROJECT_NAME}_N1H2" do |conf|
  # conf.vm.vbguest.auto_update = false
  config.vm.box = "ubuntu/focal64"
  conf.vm.hostname = "EPUAKHAW1543#{PREFIX}--N1H2-#{PROJECT_NAME}.local"
  conf.vm.network "private_network", type: "dhcp", netmask: "255.255.255.0", virtualbox__intnet: "net-1"
    
    conf.vm.provider "virtualbox" do |vb|
      vb.name = "N1H2"
      vb.gui = true
      vb.memory = (512 * 2) * 1 # 4096
      vb.cpus = 2
    
      # vb.customize ["modifyvm", :id, "--groups", "/#{PROJECT_NAME}"]
      vb.customize ["modifyvm", :id, "--graphicscontroller", "vboxsvga"]
    end
    # DHCP Config
    conf.vm.provision "shell", path: "./NAT/nat_disable.sh"
    conf.vm.provision "DHCP_netplan", type: "file", source: "DHCP/netplan_DHCP.yaml", destination: "/tmp/vagrant_task5/etc/netplan/60-task5.yaml"
    conf.vm.provision "DHCP_cloud_init", type: "file", source: "DHCP/50-cloud-init.yaml", destination: "/tmp/vagrant_task5/etc/netplan/50-cloud-init.yaml"
    conf.vm.provision "DHCP_ubuntu", type: "shell", inline: <<-SHELL
      cp -r /tmp/vagrant_task5/* /
      netplan apply
      sleep 3
    SHELL

    conf.vm.provision "routing", type: "shell", inline: <<-SHELL
      ip route add 172.16.15.0/24 via 172.16.13.254
      ip route add 172.16.14.0/24 via 172.16.13.254

      ip addres
      ip route
    SHELL
  end

  # N2H1

  config.vm.define "#{PROJECT_NAME}_N2H1" do |conf|
  conf.vm.box = "ubuntu/focal64"
  conf.vm.hostname = "EPUAKHAW1543#{PREFIX}--N2H1-#{PROJECT_NAME}.local"
  conf.vm.network "private_network", type: "dhcp", virtualbox__intnet: "net-2"

    conf.vm.provider "virtualbox" do |vb|
      vb.name = "N2H1"
      vb.gui = true
      vb.memory = (512 * 2) * 1 # 4096
      vb.cpus = 2

      # vb.customize ["modifyvm", :id, "--groups", "/#{PROJECT_NAME}"]
      vb.customize ["modifyvm", :id, "--graphicscontroller", "vboxsvga"]
    end
    # DHCP Config
    conf.vm.provision "shell", path: "./NAT/nat_disable.sh"
    conf.vm.provision "DHCP_netplan", type: "file", source: "DHCP/netplan_DHCP.yaml", destination: "/tmp/vagrant_task5/etc/netplan/60-task5.yaml"
    conf.vm.provision "DHCP_cloud_init", type: "file", source: "DHCP/50-cloud-init.yaml", destination: "/tmp/vagrant_task5/etc/netplan/50-cloud-init.yaml"
    conf.vm.provision "DHCP_ubuntu", type: "shell", inline: <<-SHELL
      cp -r /tmp/vagrant_task5/* /
      netplan apply
      sleep 3
    SHELL

    conf.vm.provision "routing", type: "shell", inline: <<-SHELL
      ip route add 172.16.15.0/24 via 172.16.14.253
      sudo ip route add default via 172.16.14.254

      ip addres
      ip route
    SHELL
  end

  # N3H1

  config.vm.define "#{PROJECT_NAME}_N3H1" do |conf|
  conf.vm.box = "ubuntu/focal64"
  conf.vm.hostname = "EPUAKHAW1543#{PREFIX}--N3H1-#{PROJECT_NAME}.local"
  conf.vm.network "private_network", type: "dhcp", netmask: "255.255.255.0", virtualbox__intnet: "net-3"

    conf.vm.provider "virtualbox" do |vb|
      vb.name = "N3H1"
      vb.gui = true
      vb.memory = (512 * 2) * 1 # 4096
      vb.cpus = 2

     # vb.customize ["modifyvm", :id, "--groups", "/#{PROJECT_NAME}"]
      vb.customize ["modifyvm", :id, "--graphicscontroller", "vboxsvga"]
    end
    # DHCP Config
    conf.vm.provision "shell", path: "./NAT/nat_disable.sh"
    conf.vm.provision "DHCP_netplan", type: "file", source: "DHCP/netplan_DHCP.yaml", destination: "/tmp/vagrant_task5/etc/netplan/60-task5.yaml"
    conf.vm.provision "DHCP_cloud_init", type: "file", source: "DHCP/50-cloud-init.yaml", destination: "/tmp/vagrant_task5/etc/netplan/50-cloud-init.yaml"
    conf.vm.provision "DHCP_ubuntu", type: "shell", inline: <<-SHELL
      cp -r /tmp/vagrant_task5/* /
      netplan apply
      sleep 3
    SHELL
  end

  # DMZ-H1

  config.vm.define "#{PROJECT_NAME}_DMZ-H1" do |conf|
  conf.vm.box = "ubuntu/focal64"
  conf.vm.hostname = "EPUAKHAW1543#{PREFIX}--DMZ-H1-#{PROJECT_NAME}.local"
  conf.vm.network "private_network", type: "dhcp", netmask: "255.255.255.0", virtualbox__intnet: "DMZ-Zone"

    conf.vm.provider "virtualbox" do |vb|
      vb.name = "DMZ-H1"
      vb.gui = true
      vb.memory = (512 * 2) * 1 # 4096
      vb.cpus = 2

     # vb.customize ["modifyvm", :id, "--groups", "/#{PROJECT_NAME}"]
      vb.customize ["modifyvm", :id, "--graphicscontroller", "vboxsvga"]
    end
    # DHCP Config
    conf.vm.provision "shell", path: "./NAT/nat_disable.sh"
    conf.vm.provision "DHCP_netplan", type: "file", source: "DHCP/netplan_DHCP.yaml", destination: "/tmp/vagrant_task5/etc/netplan/60-task5.yaml"
    conf.vm.provision "DHCP_cloud_init", type: "file", source: "DHCP/50-cloud-init.yaml", destination: "/tmp/vagrant_task5/etc/netplan/50-cloud-init.yaml"
    conf.vm.provision "DHCP_ubuntu", type: "shell", inline: <<-SHELL
      cp -r /tmp/vagrant_task5/* /
      netplan apply
      sleep 30
      sudo ip link set dev enp0s8 down
      sleep 10
      ip r
      sudo ip link set dev enp0s8 up
      sleep 30
      ip r
    SHELL
    conf.vm.provision "shell", path: "./Nginx/nginx.sh"
  end

  # DMZ-H2

  config.vm.define "#{PROJECT_NAME}_DMZ-H2" do |conf|
  conf.vm.box = "ubuntu/focal64"
  conf.vm.hostname = "EPUAKHAW1543#{PREFIX}--DMZ-H2-#{PROJECT_NAME}.local"
  conf.vm.network "private_network", type: "dhcp", netmask: "255.255.255.0", virtualbox__intnet: "DMZ-Zone"

    conf.vm.provider "virtualbox" do |vb|
      vb.name = "DMZ-H2"
      vb.gui = true
      vb.memory = (512 * 2) * 1 # 4096
      vb.cpus = 2

     # vb.customize ["modifyvm", :id, "--groups", "/#{PROJECT_NAME}"]
      vb.customize ["modifyvm", :id, "--graphicscontroller", "vboxsvga"]
    end
    # DHCP Config
    conf.vm.provision "shell", path: "./NAT/nat_disable.sh"
    conf.vm.provision "DHCP_netplan", type: "file", source: "DHCP/netplan_DHCP.yaml", destination: "/tmp/vagrant_task5/etc/netplan/60-task5.yaml"
    conf.vm.provision "DHCP_cloud_init", type: "file", source: "DHCP/50-cloud-init.yaml", destination: "/tmp/vagrant_task5/etc/netplan/50-cloud-init.yaml"
    conf.vm.provision "DHCP_ubuntu", type: "shell", inline: <<-SHELL
      cp -r /tmp/vagrant_task5/* /
      netplan apply
      sleep 30
      sudo ip link set dev enp0s8 down
      sleep 10
      ip r
      sudo ip link set dev enp0s8 up
      sleep 30
      ip r
    SHELL
    conf.vm.provision "shell", path: "./Nginx/nginx.sh"
  end
end