version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.9
  build: 
    commands:
      - npm install time
      - export BUCKET=cdp-aws-task-code-for-lambda
      - aws cloudformation package --template-file template.yaml- --s3-bucket $BUCKET --output-template-file outputtemplate.yaml
artifacts:
  type: zip
  files:
    - template.yaml
    - outputemplate.yaml