
- name: Install IIS
  win_feature:
    name: Web-Server
    state: present

- name: Create web app directory if it doesn't exist
  win_file:
    path: "{{ web_app_path }}"
    state: directory

- name: Acme IIS site
  win_iis_website:
    name: Acme
    state: started
    port: 80
    ip: 127.0.0.1
    hostname: acme.local
    application_pool: acme
    physical_path: "{{ web_app_path }}"
    parameters: logfile.directory:C:\sites\logs
  register: website

- name: Deploy web application
  win_copy:
    src: "{{ web_app_source }}"
    dest: "{{ web_app_path }}"
  notify: Restart IIS
