variables:
  IMAGE_NAME: ruslan1serdiuk/gitlab-ci
  IMAGE_TAG: python-app-1.0
  GITLAB_RUNNER_IP: "3.144.244.142"

stages:
  - test
  - build
  - deploy

run_tests:
  stage: test
  image: python:3.9-slim-buster
  before_script:
    - apt-get update && apt-get install make
  script:
    - make test


build_image:
  stage: build
  image: docker:stable
  services:
    - docker:18.09.7-dind
  variables:
    DOCKER_HOST: tcp://localhost:2375
    DOCKER_TLS_CERTDIR: "/certs"
  before_script:
    - docker login -u $DOCKERHUB_USER -p $DOCKERHUB_PASSWORD
  script:
    - pwd
    - docker build --network host -t $IMAGE_NAME:$IMAGE_TAG .
    - docker image push $IMAGE_NAME:$IMAGE_TAG

deploy:
  stage: deploy
  image: docker:stable
  services:
    - docker:18.09.7-dind
  variables:
    DOCKER_HOST: tcp://localhost:2375
    DOCKER_TLS_CERTDIR: "/certs"
  before_script:
    - docker login -u $DOCKERHUB_USER -p $DOCKERHUB_PASSWORD
    - apt install wget
  script:
    - docker run -d -p 5000:5000 $IMAGE_NAME:$IMAGE_TAG
    - wget -O- localhost:5000

deploy:
  stage: deploy
  before_script:
    - chmod 400 $SSH_KEY
    - apt update && apt install openssh-client -y
  script:
    - ssh -o StrictHostKeyChecking=no -i $SSH_KEY ubuntu@$GITLAB_RUNNER_IP "
        sudo su | docker login -u $DOCKERHUB_USER -p $DOCKERHUB_PASSWORD &&
        docker ps -aq | xargs docker stop | xargs docker rm &&
        docker run -d -p 5000:5000 $IMAGE_NAME:$IMAGE_TAG"
