network:
    ethernets:
        enp0s3:
            dhcp4: true
            dhcp4-overrides:
              use-routes: false
    version: 2

# ---
# network:
#   version: 2
#   renderer: networkd
#   ethernets:
#     enp0s8:
#     optional: true
#       dhcp4: yes