apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOnsidXNlcm5hbWUiOiJydXNsYW4xc2VyZGl1ayIsInBhc3N3b3JkIjoiV1o4enFyUndYMjhQakIiLCJlbWFpbCI6IlJ1c2xhbi5zZXJkaXVrLndAZ21haWwuY29tIiwiYXV0aCI6ImNuVnpiR0Z1TVhObGNtUnBkV3M2VjFvNGVuRnlVbmRZTWpoUWFrST0ifX19
kind: Secret
metadata:
  creationTimestamp: null
  name: client
type: kubernetes.io/dockerconfigjson
