apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: presentation-layer-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: bmukovozov.application.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: application
            port:
              number: 80